### ISSUE TITLE
Document archetype templates

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugoDocs#11]
See https://github.com/gohugoio/hugo/pull/3605

**Comment by ahmetb** [comment]
Is this issue still valid? I came here from the notice at https://gohugo.io/content-management/archetypes/

**Comment by bep** [comment]
>Is this issue still valid? 

Yes. I revamped the archetypes some time ago, but the docs don't reflect that (sadly).

**Comment by jwatt** [comment]
FWIW, as someone trying to choose between various static generators, this doesn't inspire confidence in Hugo. Your documentation currently essentially says "eight months after we changed how this critical piece works, you'll still need to read the source code to figure out how to use it because we haven't got around to updated the docs". It makes Hugo look either poorly maintained, or else like a project that doesn't care too much about their users. That's a shame (and a bit weird) because there has obviously been a lot of great work gone into both Hugo and its website.

**Comment by bep** [comment]
>FWIW, as someone trying to choose between various static generators, this doesn't inspire confidence in Hugo. Your documentation currently essentially says  "eight months after we changed how this critical piece works, you'll still need to read the source code to figure out how to use it because we haven't got around to updated the docs"

@jwatt

This isn't remotely close to being a "critical piece" of Hugo. It is a utility function, and the current docs is correct -- just not complete. You can read about how the new features for that utility function in the relevant release notes.

>It makes Hugo look either poorly maintained

Hugo is open source software. People contribute their free time to it, that there are open issues/unfinished work goes without saying.  

But thanks for your input. I will make sure to have a look at your open source side projects to get some inspiration for how it should be done.

If you have more input on this, I suggest you create a new thread on [Hugo Discussion Forum](https://discourse.gohugo.io/).
