### ISSUE TITLE
The list of available emojis is inaccurate 

### ISSUE THREAD

**Issue by jbleduigou** [gohugoio/hugoDocs#1163]
I believe there are some inaccuracies in the list of emojis described in page content/en/functions/emojify.md

For instance ``` :bowtie: ``` does not convert properly.

My understanding is that the actual code map used is https://github.com/kyokomi/emoji/blob/master/emoji_codemap.go
Based from http://www.unicode.org/emoji/charts/emoji-list.html

**Comment by jmooring** [comment]
Background information; not actionable.

The documentation points to <https://www.webpagefx.com/tools/emoji-cheat-sheet/> from these pages:

- <https://gohugo.io/functions/emojify/>
- <https://gohugo.io/getting-started/configuration/>

The referenced cheat sheet contains 877 emoji codes (e.g., `:foo:`), 17 of which are not recognized by Hugo; they are unique to GitHub. See <https://emojipedia.org/github/>.

Hugo's code map is an amalgamation of four sources, currently with 4670 codes representing 2995 unique emojis (1675 of the codes are aliases). Hugo does not render 55 of the 4670 codes due to the presence of one or more of these characters: `( ) ’ Å & ô ç é ã í . * # ! ñ`. 

While emojis are somewhat standardized through the Unicode Consortium (<https://home.unicode.org/emoji>), _the codes used to represent them are not_. That is why there are 1675 aliases in Hugo's implementation. For example, this emoji (:no_good:) can be written as any of the following in Hugo, though only the first three are recognized by GitHub:

```
:no_good: 
:ng_woman: 
:no_good_woman: 
:woman-gesturing-no: 
:woman_gesturing_NO: 
:woman_gesturing_no:
```

An ideal cheat sheet for Hugo users would:

- Have two versions
  - Curated (most commonly used, a few hundred at most)
  - Complete (all 2995 symbols)
- Organize emojis by category, and perhaps by sub-category on the complete list
- Provide one code for each symbol
  - Content authors want to know how to insert a symbol; they don't need to know about the aliases
  - Among several alternatives for the same symbol, choose most commonly used based on GitHub, Twitter, etc.
- Contain keywords to facilitate search (Ctrl+F in browser)
- Exist on a single page to facilitate search (Ctrl+F in browser)
- Load fast, probably using embedded PNGs

Two of the best sources for information are <https://emojipedia.org/> and <https://unicode.org/emoji/charts/>, but neither of them contain codes (e.g., `:foo:`). Again, while the symbols are somewhat standardized, the codes used to represent them are not.

The best existing cheat sheet that I've been able to find is... the one we're using now. It it (somewhat) curated, categorized, easy to use, and loads fast. And Hugo properly renders 98.06% of the codes.

**Comment by jbleduigou** [comment]
Thanks @jmooring for this detailed analysis!

**Comment by jmooring** [comment]
With https://github.com/gohugoio/hugo/pull/11593 we can now include a definitive list in the documentation.
