### ISSUE TITLE
Document js.Build's externals + test out shimming

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#1178]
See https://github.com/evanw/esbuild/issues/283

/cc @regisphilibert

**Comment by UtkarshVerma** [comment]
@bep I've tested out shimming and it works. I tried my best with the documentation, but since I'm new to Node.js, there might be some mistakes. I hope this PR  at least serves as a starting point for this issue, and helps out other developers who might be wanting to load external dependencies, like I was.
