### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by rykov** [gohugoio/hugoDocs#12]
Previously, the [spf13/hugo](/spf13/hugo) repo was all Apache 2.0.  Now that it's been split up, it's probably best to copy the LICENSE file to all the new repositories as well.

**Comment by felicianotech** [comment]
It's very common to have the code under a code license and then the content under some Creative Commons license.

**Comment by bep** [comment]
@spf13 thoughts?

**Comment by spf13** [comment]
This is a mixture of code and content. 

First of all, we can't just drop the existing license. It needs to stay present as existing contributions were made under that license. The repo needs the Apache 2.0 license.

Secondly, the content had been published copyright Steve Francia, at least on the home page. There isn't one on any of the other pages that I can see today. I fine with releasing the content under the right CC license. As the copyright holder I can do that. Now I'm sure others contributed significantly to the content and I'm not a lawyer so I'm not sure if they would also need to approve of the change.  

We need a CLA for this project to ensure that the code is submitted under the Apache 2 license and is unencumbered and also that the content contributed is ok with being released under the CC license we choose.

**Comment by bep** [comment]
@spf13 the "copyright in the footer" is as I see it a left-over from when we did the CLA/Apache migration. The Hugo docs site has lived in the `hugo` repo clearly marked with a Apache license, and the CLA signed for all the docs contributions has been marked accordingly. 

I have created #18 to track the fix of the footer text to match what is clearly stated in the Go source code. As I understand it, the artwork (logo etc.) is yours and not published with an open license, so that should be stated specifically. But the **content** is currently Apache 2 and Copyright the Hugo Authors.

**Comment by spf13** [comment]
That makes sense to me.

**Comment by bep** [comment]
But I'm not sure what Creative Commons vs Apache 2 gives us ... I don't think we can relicense without asking the contributors, and that seems like too much work.

**Comment by felicianotech** [comment]
It's just the idea that Apache license is made for code while creative Commons is made for blogs, articles, writing etc. Maybe projects thus use a coding license for the code and CC for the content. https://softwareengineering.stackexchange.com/questions/285123/how-to-display-clarify-the-licence-for-code-in-a-blog

From the original repo, everyone (including me) signed a CLA. Usually CLAs have the user give the permission to the owner to relicense their work or in the case of a CLA like Canonical has, the user gives up their copyright completely to the project.

I haven't read the original Hugo CLA in detail to be honest but I will now.

Regardless, yes a license is needed and it'll at least be the Apache one since that was original. Makes sense.

**Comment by felicianotech** [comment]
This is what I signed (https://cla-assistant.io/gohugoio/hugo) and while I'm no lawyer, I don't see anything about relicensing or giving up that right. So I guess the Apache license all the way makes sense here.
