### ISSUE TITLE
bug: transparent code snippet 

### ISSUE THREAD

**Issue by avats-dev** [gohugoio/hugoDocs#1341]
So, many code snippets get enlarged when hovered over and they overlap with right side bar and hence they should not be transparent then. I am attaching a bugging instance I found [here](https://gohugo.io/getting-started/quick-start/).

- **Normal code snippet (the correct way)**

![Quick Start _ Hugo - Google Chrome 2021-02-19 03-50-10](https://user-images.githubusercontent.com/35889327/108429872-90699000-7266-11eb-9267-b5fcba6fe69f.gif)

- **Wrong code snippet**

![Quick Start _ Hugo - Google Chrome 2021-02-19 03-52-45](https://user-images.githubusercontent.com/35889327/108429911-9c555200-7266-11eb-9a89-f3fb32de6348.gif)

The markdown file for this page is [here](https://github.com/gohugoio/hugoDocs/blob/master/content/en/getting-started/quick-start.md) but I don't know how can it be resolved from there. 

- [x] So, if anyone could help me out a bit, I would like to resolve this.

**Comment by sebastiaan-lampo** [comment]
The difference between those two code blocks is the invocation of the bash highlighter. The highlighter adds a div with class highlight around the code block which triggers the `.highlight pre` rule in [/resources/_gen/assets/css/output/css/app.css...](https://github.com/gohugoio/hugoDocs/blob/84444120ffe8d92f6d153ed021b4a23a390fdbe0/resources/_gen/assets/css/output/css/app.css_d11fe7b62c27961c87ecd0f2490357b9.content).

Removing the following two rules from that style block solves the transparency and distracting padding inside the expanded code block:
```
  background-color: inherit;
  padding: 0.5em;
```

I suspect that file is generated by scss or something because it's not designed to be human readable at all. This is where my knowledge ends and I cannot advise on what the right spot is to correct this.

**Comment by thewheat** [comment]
This issue and #1368 are duplicates
