### ISSUE TITLE
Example of sorting authors map doesn't work as documented

### ISSUE THREAD

**Issue by chalin** [gohugoio/hugoDocs#1365]
This is a followup issue to #1344, which improves the `sort` function documentation but leaves in one example that doesn't work as documented. 

Context:

- https://github.com/gohugoio/hugoDocs/pull/1344#issuecomment-801107070
- https://github.com/gohugoio/hugo/issues/8335

cc @jmooring @nate-double-u @zacharysarah

**Comment by jmooring** [comment]
Are these comments sufficient to move this forward?
<https://github.com/gohugoio/hugo/issues/8335#issuecomment-801285809>

**Comment by chalin** [comment]
> Are these comments sufficient to move this forward? https://github.com/gohugoio/hugo/issues/8335#issuecomment-801285809

Yes, I'll put something together as soon as I can.

**Comment by jmooring** [comment]
@chalin: When updating the documentation we must be specific about the source of the data.

When we are sorting `params` data (either site or page), we must provide a lowercase key because Hugo converts `params` keys to lowercase for internal storage. See https://github.com/gohugoio/hugo/issues/8335#issuecomment-801285809.

However, when sorting data from other sources such as `site.Data.foo` or dictionaries generated in template code, the sort key is case sensitive.

The same rules apply when using `where`.

Yeah, I don't like it either.

cc/ @moorereason
