### ISSUE TITLE
Include documentation for hugo-extended intallation on MacOS

### ISSUE THREAD

**Issue by dburov190** [gohugoio/hugoDocs#1468]
There is currently no information on how to install extended hugo on MacOS: https://gohugo.io/getting-started/installing/#macos

I'm proposing to add a section for MacPorts with the following line:
```zsh
sudo port install hugo +extended
```
Not sure how this is done with `brew` though.

**Comment by hieu6** [comment]
I don't yet know how to contribute to docs, will leave this as a note for future me (or anyone else).

found this README.md about how to install extended version. found only after I downloaded extended version directly from Releases page 😅

edited for clarity.

---

## Install Hugo (easiest)

Use the installation instructions in the [Hugo documentation](https://gohugo.io/getting-started/installing/).

## Build and install Hugo using `Go`

### 0. Prerequisite Tools

* [Git](https://git-scm.com/)
* [Go >= v1.16](https://golang.org/dl/)

### 1. use Go to install the latest Hugo release

_note: The below assumes macOS. If Windows, substitute `$HOME` with `%USERPROFILE%`._

Hugo builds using Go Modules. `git clone` the latest release of Hugo into a new folder, and install using `Go`.

```bash
mkdir $HOME/src  # create new directory
cd $HOME/src  # change directories
git clone https://github.com/gohugoio/hugo.git
cd hugo
go install
```

### (Optional) Install the Extended version in order to use advanced features, such as Hugo Modules or Sass/SCSS

`CGO_ENABLED=1` temporarily enables `CGO` to compile the extended Hugo install fr you.

```bash
CGO_ENABLED=1 go install --tags extended
```

**Comment by thewheat** [comment]
I think the brew installation includes is hugo-extended
```
$  hugo version
hugo v0.88.1+extended darwin/amd64 BuildDate=unknown
```

From the homebrew formula
https://github.com/Homebrew/homebrew-core/blob/7305b83030f82a86a7b5c454b3e016dc3576e025/Formula/hugo.rb#L22

```
    system "go", "build", *std_go_args(ldflags: "-s -w"), "-tags", "extended"
```

And commit message confirming it is extended https://github.com/Homebrew/homebrew-core/commit/c49f3560dd1f31bdb2cebbe5b584d4a87f54a3e0

**Comment by thewheat** [comment]
I've made a PR https://github.com/gohugoio/hugoDocs/pull/1555 to clarify the brew install is the extended version and added the MacPorts install as well 

I think the install instructions from source https://gohugo.io/getting-started/installing/#source covers what is mentioned in https://github.com/gohugoio/hugoDocs/issues/1468#issuecomment-912583871 already

**Comment by ColinLondon** [comment]
I'm an author, not a dev! Can someone please help? I can install Hugo with:

```brew install hugo```

But how do I use brew to install the Extended edition (I have the Lotus Docs theme that apparently requires it).

Thanks guys.
