### ISSUE TITLE
functions: Document strings.TrimPrefix and TrimSuffix

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugoDocs#148]
See https://github.com/gohugoio/hugo/pull/3803

**Comment by rdwatters** [comment]
@moorereason `.TrimPrefix`, `.TrimSuffix`, `.TrimRight`, and `.TrimLeft` need to be called with the namespace?

```
{{ $cowsound := "Moooo" }}
{{ $cowsound | strings.TrimRight "o"}}
=>
"M"
```

That is, not `$cowsound.TrimRight "o"` or `$cowsound | TrimRight "o"`, correct?

I'm wondering if this will be as clear/intuitive to users who are used to pipes and, for example, `.Format`, etc.

cc/ @digitalcraftsman

**Comment by bep** [comment]
>need to be called with the namespace?

This issue is about strings.TrimPrefix and strings.TrimSuffix -- but for those, the answer is: Yes.

**Comment by rdwatters** [comment]
Right, wanted an answer to both this and https://github.com/gohugoio/hugoDocs/issues/147

**Comment by rdwatters** [comment]
My real question is about whether this usage will be as intuitive to Hugo users. Thoughts, @bep?

**Comment by bep** [comment]
>My real question is about whether this usage will be as intuitive to Hugo users. 

It will not be if we do not document it. I will be short here, because we cannot repeat these discussions every month:

* The only reason these funcs were added to Hugo is the new namespaces. So, I don't really care about the "intuitiveness" of it, it is much better than not having those funcs.
* New template funcs that gets added with an alias should be really important (i.e. used a lot, like `where`etc.)

So, if you don't think they add value as is, please open an issue about removing them.

**Comment by rdwatters** [comment]
Settle down. I think they're great and never mentioned anything about not using them.

**Comment by bep** [comment]
Then please don't start a new discussion for every small _todo task_ there is.
