### ISSUE TITLE
Improve quickstart & documentation

### ISSUE THREAD

**Issue by m0nt3cr1st0** [gohugoio/hugoDocs#1498]
Hi everyone!

I'm a complete newbie to Hugo and Go (although I do have some experience with IT and programming in general)

While trying to follow the [Hugo quickstart guide](https://gohugo.io/getting-started/quick-start/)  I came into some problems (specially in regards making the ananke theme.  More specifically an error mentioning something like `function "hugo" not defined`  and a path to the ananke installation directory.

I solved the error by installing Go, although it wasn't that straight forward as it seems the go version that my Ubuntu 18.08 installation has in its repository is not supported by the theme anymore.

Do you think it would make sense to include a section in the guide adding Go as a requirement/nice-to-have? 
I assume is not a requirement per se (otherwise it would be on the guide)  but at least a warning box that it will be nice to have if you want to use the proposed theme.

It could be a nice help for newcomers not so experienced in troubleshooting these missing binaries problems!

**Comment by hieu6** [comment]
hello @m0nt3cr1st0

Go is a prerequisite for non-basic use cases such as using [Hugo Modules](https://gohugo.io/hugo-modules/use-modules/) or installing the  [extended version.](https://gohugo.io/getting-started/installing/). the latest version of Go is listed as a requirement in those places.

I've played around on many `hugo new site` at this point, and sometimes even after repeating same steps a dozen times, I'll run into an error I can't figure out. usually due to a typo, ha. it's been a while since you've posted, but I am wondering if this was a case of user error.

-hieu

**Comment by m0nt3cr1st0** [comment]
Hi @hieu6  thanks for your response,

I'm pretty sure there was no type (I managed to replicate the issue), but I can't discard has something to do with my machine package repositories.

I guess it's not a big deal as I was able to sort it out after some googling, if no one else is complaining about it, then the effort of troubleshooting this is probably not worth! Thanks anyway for your time put on this!
