### ISSUE TITLE
Hugo's documentation is difficult to read

### ISSUE THREAD

**Issue by codlin** [gohugoio/hugoDocs#1532]
Hugo's documentation is difficult to read. 
Here is a proposal. I hope that the team will invent as few professional vocabulary as possible when writing documents, and try to use simple vocabulary to express the meaning. This will help Hugo spread among non-native English speakers.

**Comment by Linux-Geezer** [comment]
It would probably be more helpful if you provide some example of what you're having difficulty reading. Hugo is software, so I'm thinking one should expect some professional vocabulary. Just my two cents...

**Comment by libinglong** [comment]
@Linux-Geezer 
I am a new user of hugo.
Frankly, It's so diffcult for me to understand the document.
For example, at https://gohugo.io/templates/lookup-order/#examples-layout-lookup-for-regular-pages
What is the meaning of "Regular Pages"?
What is the difference between 'Single page in "posts" section' and 'Single page in "posts" section with layout set'?

Finally I turn to jekyll.
When I read jekyll document, I can qucikly understand how to build a site.
When I come back to hugo, I understand better because I have read the jekyll document.

There is a guide for how to write a document for Spring.
https://github.com/spring-io/spring-asciidoctor-backends/blob/main/guides/style-guide.adoc#the-goal-and-the-audience

I think hugo should focus on the ducument right now other than the more complex technolgy if hugo want to go further.

**Comment by genetikdisoda** [comment]
Jekyll was a bliss to use because the documentation was flawless. Hugo's issue is that it is so versatile, that the many ways of doing one thing creates a confusion for many a new users.

**Comment by jmooring** [comment]
@genetikdisoda 

Each of your comments generates a notification for everyone on the team and everyone watching the repository. Please make sure you are adding value.

**Comment by genetikdisoda** [comment]
I am. Otherwise I wouldn't be checking the issues. Or do you police how many comments users make? I am outta here either way.

**Comment by bep** [comment]
Thanks for the feedback.
