### ISSUE TITLE
Add section about data types

### ISSUE THREAD

**Issue by Wuzzy2** [gohugoio/hugoDocs#1551]
Data types are quite important in Hugo, but there's no real dedicated section for those data types yet. You have to somehow piece this information together from various scattered pages, and even that seems incomplete.
I suggest to add a section to the help explaining only the data types.

**Comment by jmooring** [comment]
Closing this due to several recent changes:

1. Every [function](https://gohugo.io/functions/) and [method](https://gohugo.io/methods/) in the documentation now includes its return type
2. We have fixed the handful of unexpected return types (e.g., `collections.Delimit` now returns a string)
3. We have created a glossary of terms that describes common data types

The remaining hurdle, when/why to use `safe.HTML` and friends, will be addressed in [#2252](https://github.com/gohugoio/hugoDocs/issues/2252)
