### ISSUE TITLE
Community Articles & Deploying to S3

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/hugoDocs#197]
The old docs site used to have a community supported articles section where many great community articles were linked. I had a thorough write-up on S3 + CloudFront deployment with HTTP/2 + TLS. Has that information been removed? I can't seem to find it from the primary navigation.

https://habd.as/zero-to-http-2-aws-hugo/

**Comment by digitalcraftsman** [comment]
Yes, this section has been removed while discussing the rewriting of the internally. We weighted the pros and cons of keeping it and came to the conclusion this list contained indeed great and high quality articles.

On the other hand it was a huge table that was unlikely to be browsed in this format. Furthermore, we didn't checked the quality of the article's content itself. Some might be wrong, outdated or unreachable due to a broken HTTP link.

Overall, this meant that the maintenance of the articles list meant more overhead added to the Hugo maintainers that didn't outweighed the pros. We rather thought about that this kind of articles should be shared via the forum or on Twitter were (the high quality) ones are retweeted or otherwise promoted.

Feel free to let us know your point of view.

**Comment by jhabdas** [comment]
Thanks for the clarification. It's my opinion if it's not search, it's a sink. Social is good for all of 5 minutes. If the articles weren't vetted but they served a purpose for a time that's cool. Though perhaps it's worth creating a `/tweet` section on the side to share that info—linkrot is inevitable.

**Comment by budparr** [comment]
FWIW, @jhabdas I have over 70 Hugo related articles collected here: https://www.thenewdynamic.org/tool/hugo/

**Comment by digitalcraftsman** [comment]
> Though perhaps it's worth creating a /tweet section on the side to share that info—linkrot is inevitable.

Perhaps we can add a note that adds a notice or links to aggregators like @budparr's thenewdynamic.

**Comment by jhabdas** [comment]
@budparr thanks for getting two of my articles listed. has appreciate. @digitalcraftsman I once ran an experiment linking twitter feeds to a tweet path on a website. google loved it.
