### ISSUE TITLE
`pageRef` missing?

### ISSUE THREAD

**Issue by bwc69151** [gohugoio/hugoDocs#2020]
https://gohugo.io/variables/menus/ cc @jmooring

**Comment by jmooring** [comment]
@bwc69151 

I commented this out:
<https://github.com/gohugoio/hugoDocs/blob/master/content/en/variables/menus.md?plain=1#L39-L48>

As I was reworking the menu pages, I could not think of a reason to use `.PageRef` in a menu template, and thought it might be confusing (e.g., "Should I use `.URL` or .`PageRef`?).

The `pageRef` _property_ is documented here:
<https://gohugo.io/content-management/menus/#define-in-front-matter>

There may be a good reason to use `.PageRef` in a menu template, but I couldn't think of one. Comments?

**Comment by bwc69151** [comment]
Two reasons why I asked:
1. I saw several recommendations from you on this repo to use it for internal links.
2. The search in the Hugo site (gohugo.io) still points to the menu variables section for pageref. 
So, unless you did change your mind on using pageref?

**Comment by jmooring** [comment]
There's some confusion here, which is why I removed the reference from the menu VARIABLES page.

You set the `pageRef` PROPERTY when defining a menu entry:
<https://gohugo.io/content-management/menus/#properties-site-configuration>

And you use the `.URL` VARIABLE in your templates.

The search index is updated periodically (once a week I think). When I search for `pageref` it shows up where it should.
