### ISSUE TITLE
Documentation Content Width is Too Narrow

### ISSUE THREAD

**Issue by xM8WVqaG** [gohugoio/hugoDocs#2086]
The default documentation `max-width` is too narrow causing the `pre` rendered code blocks to all overflow on a desktop. Seeing as they are the most important content on the pages that document commands this is very frustrating!

**Browser:** Firefox 107.0.1
**OS:** Linux / Flatpak
**Screen resolution:** 2560x1440
**Example page with the problem:** <https://gohugo.io/commands/hugo/>

![image](https://github.com/gohugoio/hugoDocs/assets/44505331/10360e13-53f0-4cca-b07a-dd919c78fc71)

Manually hacking the CSS to replace `.mw7` `max-width: 48em` with `max-width: 60%` and removing `max-width` from `.measure-wide-l` gives this:

![image](https://github.com/gohugoio/hugoDocs/assets/44505331/a2ed4df3-80ef-49c4-bf23-f1010e0907f3)

Which looks more like what was originally intended with the `.w-60-l` class which has `width: 60%` set. Although I've not attempted to understand how the CSS is actually written, so this shouldn't be taken as a suggestion of the best change.

**Comment by BWPanda** [comment]
Agreed!

Looks like this might be fixed in the dev version already, at least by comparing other pages (as the CLI/Commands page doesn't seem to exist on the dev site):
- https://gohugo.io/functions/getpage/
- https://next--gohugoio.netlify.app/documentation/functions/getpage/

![image](https://github.com/gohugoio/hugoDocs/assets/2385329/af7b22e2-99c2-4a08-ad39-41fcc475eb19)

![image](https://github.com/gohugoio/hugoDocs/assets/2385329/36d25de4-8cd2-44a5-91f4-c149ff499122)

**Comment by jmooring** [comment]
I agree this needs some attention. Please create an issue in the relevant repository:
<https://github.com/gohugoio/gohugoioTheme>
