### ISSUE TITLE
Add a page on sourcehut deployment

### ISSUE THREAD

**Issue by antoinentl** [gohugoio/hugoDocs#2145]
sourcehut provide a very interesting (and simple) deployment and hosting. It's not free but very affordable. I will do a PR in the next days if some people are ok with that.

Informations:

- sourcehut pages: https://srht.site/
- example of setup for Hugo: https://git.sr.ht/~sircmpwn/pages.sr.ht-examples/tree/master/item/hugo.yml

Todo list:

- [ ] assumptions: sourcehut is email based
- [ ] baseURL: with or without custom domain
- [ ] setup the build manifest: example from https://git.sr.ht/~sircmpwn/pages.sr.ht-examples
- [ ] git scenario
- [ ] extra information/documentation

**Comment by jmooring** [comment]
@antoinentl Thanks for the suggestion.

My take on this... with so many free options (GitHub, GitLab, Netlify, etc.) I think the majority (99.5% ?) of site developers will not signup for an account. I was going to try it out this morning, but am not going to bother because they want payment information.

![image](https://github.com/gohugoio/hugoDocs/assets/335669/2e6b0efb-a889-4e8a-a45f-c1ef84847b39)

Unless you can make a strong case, I am inclined to close this issue.

**Comment by antoinentl** [comment]
Thanks for pointing this @jmooring! I agree on the issue of free access, but it's not just about that. I think it's fair/interesting/positive to purpose an option based on a platform which is not a big enterprise, and 100% open source/free software. Paying for a (good) service is not a big issue, especially when companies like Netlify are cutting jobs to make more money. GitHub, GitLab and Netlify are free for the users, not for the community.

**Comment by jmooring** [comment]
I have no way of verifying or maintaining the documentation without spending money, and given the limited use by the Hugo community it is not a good investment of my time. I think this is better for a tips and tricks topic on the [forum](https://discourse.gohugo.io/).

**Comment by fu-sen** [comment]
Since I commented on issues from three years ago, you might want to separate them.
It seems you have lightly investigated and closed the sourcehut pages.

If you use the following Quick Start steps, it is fully available to free users.
Moreover, this procedure mentions Hugo. (Sourcehut official source!)
https://srht.site/quickstart/

If you entrust the build to sourcehut, it will be a paid plan.
https://srht.site/automating-deployments/

Therefore, you can use SourceHut Pages for free by building locally or with other services.

username.srht.site can only be used for each user, but you can also use your own custom domain, with no restrictions.
In this case, Let's Encrypt is issued during the build phase, so you will refer to it at https:.
https://srht.site/custom-domains/

Recently, subdomains that can't be used on Vercel or Netlify have been created.
Cloudflare Pages has also migrated to Cloudflare Workers static assets, and the situation is becoming the same.
In that case, sourcehut pages are an alternative option.

Unlike GitHub Pages, you don't have to rely on Git. For some individuals, this will be an advantage.

https://sourcehut.org/blog/2021-02-18-sourcehut-pages/

Also, You can also use the curl procedure described on this page! You do not need to install hut.
