### ISSUE TITLE
hugoDocs branch model

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#22]
There seems to be some confusion about what branches to use for what, and I guess we have learned some lessons by living with this new setup for a little.

**I would say that if the majority of the ongoing changes are relevant for the current release version of Hugo, then those changes should be pulled directly into master, and we should deploy from master.**

But then we should get rid of `stable`, as stable would then be the `tags`.

So, given the current status:

* `master`: 0.24.1
* `dev`: 0.25-DEV
* hugo/docs (which is now a Git subtree): 0.25-DEV

* So most PRs in `hugoDocs` goes into `master` and directly live. Some changes will have to be pulled into `dev` and wait for a new release.
* Some PRs in `hugo` will contain docs-changes. I guess we'll merge those into `dev` at intervals (at least every release).
* On new release: Bump and tag `master` to new version `0.25`, bump `dev` to `0-26-DEV`.

So 2 branches.

Does that make more sense?

/cc @digitalcraftsman

**Comment by digitalcraftsman** [comment]
> But then we should get rid of stable, as stable would then be the tags.

`stable` is has already been removed which I'm fine with. The tags make this branch superfluous.

> Some PRs in hugo will contain docs-changes. I guess we'll merge those into dev at intervals (at least every release).

That's done to keep pull requests atomic which contain documentation for an upcoming feature, right?

---

Let's pretend we've a new release around the corner. `dev` contains commits like typo fixes that are already live (i.e. are in `master` as well) and documentation that can't be released before the next release.

How do we merge the latter kind of commits into `master` so that they can go live as well? The commit log of `master` and `dev` will diverge over time.

**Comment by bep** [comment]
Why would `dev` contain fixes from master?

**Comment by bep** [comment]
To make this clear:

When doing a new release `dev` is merged into `master` and master is tagged.

**Comment by rdwatters** [comment]
There are three scenarios:

1. Hugo release users submitting PRs to published docs
2. New features implemented by the Hugo team needing documentation
3. Hugo users submitting feature PRs that need to be documented

1. My assumption would be that Hugo users would submit PRs directly to `master` since said changes are likely a) typos or small usage issues or b) real-world examples or further explanations of existing features in the wild (i.e., in the current *release*).

2. Changes to the `dev` branch (of the docs) would need to be managed by the Hugo team, since the Hugo team is responsible for adding and implementing said features and would therefore be most well suited to write the first draft of content for said new feature (e.g., @bep was, obviously, the most well-qualified person to write the first draft of copy for custom outputs).

3. This is the trickiest: feature PRs submitted by users, which would require a PR of `dev`, but this could be explained on an as-needed basis or, perhaps more effectively, be a requirement for the PR?

Merging issues ("pains") are inevitable with content, and I agree that there is little value in worrying too much about them now. I'm happy to take this on as much as possible too since it's an editorial role, and I've been doing this manually for the last 7 months anyways :smile:

**Comment by bep** [comment]
From a purely practical standpoint, it would be good if:

* All typo/showcase type or PRs goes to hugoDocs/master
* All doc for new features goes to hugo/master in a combo with the code
* All bigger doc updates that does not match current Hugo goes into `dev` whatever that is. This would ideally mean that people create a GH PR with `dev` as the target.

In the above, most ongoing changes could mindlessly go into **a master**.

**Comment by bep** [comment]
Let us reopen this to get it nailed. Let us assume that both `dev` and `hugo/docs` wants to keep track of changes in master.

From `dev` we do `git pull --rebase origin master`

So, **we always do a rebase in that direction** so the commit history will never diverge.

So, when we are ready to release, we do in `hugoDocs`:

```bash
git checkout master
git merge dev
git merge -s docs hugo/master
```

One thing I'm not sure about, which need some testing is how we can (or if we really want to), get changes from `hugoDocs/master` into `hugo/docs` with squashing and then get a clean merge back.
