### ISSUE TITLE
Sort entries in doc sidebar

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugoDocs#2208]
Currently, the entries in the left sidebar of the Hugo documentation are (seemingly) not sorted at all. Example under the heading "Templates":
- Overview
- Templating
- Template lookup order
- Base templates and blocks
- Single page templates
- List templates
- Homepage template
- Section templates
- Taxonomy templates
- Pagination
- Content view templates

The first view serve as introduction into templating (though personally I find the "Overview" useless as it doesn't do anythig but link to other parts). Starting with "Single page templates", there doesn't seem to be any kind of system to the order of appearance. It is certainly not alfabetic. Then there's "Content view templates" which seems an odd name, since list and single view templates also handle content (as does the homepage template etc). 
I'd suggest to at least order the different "templates" entries alfabetically. That doesn't help newbies, but at least someone knowing what they're looking for can find it easier.

**Comment by jmooring** [comment]
> I find the "Overview" useless

I've added an introductory paragraph.

> there doesn't seem to be any kind of system to the order

The introductory paragraph addresses this, at least to some extent.

> Content view templates

This name was selected long ago. I'm not in love with the name either, but at the moment I can't think of anything better. A "content view template" is like a partial, but with three key differences:

1. They conform to Hugo's established [lookup order](templates/lookup-order/)
3. They can only be called with the `.Render` method on the `.Page` object
4. You cannot control the context; content view template receive the context of the page from which they are called.

> order the different "templates" entries alphabetically

The order is by design. It may not be perfect, but the intent is progressive disclosure.

> someone knowing what they're looking for can find it easier

I think a presenting the information in a (somewhat) logical order is more important. In relation to finding something quickly, (a) the number of entries isn't terribly long, and (b) that's what search is for.
