### ISSUE TITLE
Hugo docs should include an actual tutorial

### ISSUE THREAD

**Issue by brassy-endomorph** [gohugoio/hugoDocs#2257]
The docs suffer from "man page syndrome" in as much as they show every possible option but don't teach how to use Hugo. As someone with over a decade of web development experience, I can't figure out how to actually build a bare bones simple site.

For example, do I have to install themes? No, ok, so why can't I get a single `_index.md` to display? I have no idea, and the docs offer nothing that seems to answer that question. What needs to go in the front matter? What goes where in the layouts directory?

I am unable to get the most basic "hello world" single page website to work if I start from scratch, so I can't imagine how I'd actually figure out how to build something complex.

Rust has [The Book](https://doc.rust-lang.org/stable/book/) that very slowly incrementally adds from the simplest topics to the full range of features. Something like this would be extremely helpful.

**Comment by jmooring** [comment]
The goal of the [quick start guide](https://gohugo.io/getting-started/quick-start/) is to help new users quickly get started, producing an aesthetically pleasing site with as few key strokes as possible.

With v0.118.0 and later, the first command in the quick start guide (`hugo new site quickstart`) offers an alternate path:

```text
1. Change the current directory to /home/jmooring/temp/my-site.
2. Create or install a theme:
   - Create a new theme with the command "hugo new theme <THEMENAME>"
   - Install a theme from https://themes.gohugo.io/
3. Edit hugo.toml, setting the "theme" property to the theme name.
4. Create new content with the command "hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>".
5. Start the embedded web server with the command "hugo server --buildDrafts".
```

Under step 2, if you create a new theme instead of installing an existing one, you get a simple skeleton demonstrating basic features such as:

- Directory structure
- Content structure
- Page bundles
- Date localization
- Menus
- Taxonomies
- Partial templates (including cached partials)
- CSS inclusion
- JavaScript inclusion
- Static files

Although I understand that everyone learns differently, I find the "scaffold then examine" approach to be far more efficient than the "building a Hugo site the hard way" approach.

For alternate learning approaches, see:
<https://gohugo.io/getting-started/external-learning-resources/>

**Comment by gunteet** [comment]
This would be better discussed in the support forum.

**Comment by jmooring** [comment]
Rough order of magniture (ROM): 100 hours
