### ISSUE TITLE
Installation instruction for Gentoo incomplete

### ISSUE THREAD

**Issue by gen2thomas** [gohugoio/hugoDocs#2386]
see: https://gohugo.io/installation/linux/#gentoo

The package [is currently masked](https://packages.gentoo.org/packages/www-apps/hugo), so this should be sufficient:
create a file "/etc/portage/package.accept_keywords/hugo" and add the content

"=www-apps/hugo-0.121.0 ~amd64"

Maybe a reference to "https://wiki.gentoo.org/wiki/Hugo" would be better? (Yes, there is the unmask part also missing.)

**Comment by jmooring** [comment]
I'm not an Gentoo expert, but I thoroughly tested the installation instructions using a virgin installation of Calculate (cld-20231204-x86_64.iso). 

@rahilarious I would appreciate your input on this.

**Comment by rahilarious** [comment]
> see: https://gohugo.io/installation/linux/#gentoo
> 
> The package [is currently masked](https://packages.gentoo.org/packages/www-apps/hugo), so this should be sufficient: create a file "/etc/portage/package.accept_keywords/hugo" and add the content
> 
> "=www-apps/hugo-0.121.0 ~amd64"

This is happening because as of now package www-apps/hugo is in beta (~ keyword) and there is no stable version, so I've filed a bug https://bugs.gentoo.org/921501 to stabilize package which would resolve this issue.

But anyways, it is expected from a Gentoo user to know how to use packages from beta (~ keyword) but if you still want to add instructions maybe link wiki page https://wiki.gentoo.org/wiki//etc/portage/package.accept_keywords

> Maybe a reference to "https://wiki.gentoo.org/wiki/Hugo" would be better? (Yes, there is the unmask part also missing.)

I agree wiki page should be mentioned somewhere but it doesn't have any instructions on how to use package  in ~ beta.

**Comment by jmooring** [comment]
> it is expected from a Gentoo user to know how to use packages from beta

I agree.

> so I've filed a bug https://bugs.gentoo.org/921501 to stabilize package which would resolve this issue

Thank you.

Given the above, I am inclined to leave the documentation as is.
