### ISSUE TITLE
Can you make this discourse thread public?

### ISSUE THREAD

**Issue by lobopraveen** [gohugoio/hugoDocs#315]
Page - https://gohugo.io/troubleshooting/eof-error/

The second link under Discussion Forum References takes me to discourse site and asks me to login to see the topic. this link - http://discourse.gohugo.io/t/eol-f-in-archetype-files/554

Is there a reason behind allowing only logged in members to see it?

**Comment by kaushalmodi** [comment]
1. That troubleshooting page has been removed for a while now as that issue got fixed in https://github.com/gohugoio/hugo/commit/78e9229c52dfdaf335673b171a3d66fc1ace8d9e (Issue https://github.com/gohugoio/hugo/issues/776).
2. About the reason for "only logged members can see it", why not create a login.. you have an option to log in using your GitHub credentials.

**Comment by lobopraveen** [comment]
1. ok.
2. I think you forgot to mention the reason but it doesn't matter anymore as that page has been removed. Also, creating a login is not the solution to the problem but a workaround. 
Thanks!
