### ISSUE TITLE
Trim the tags usage

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#32]
```bash
Started building sites ...
Built site for language en:
0 of 7 drafts rendered
0 future content
0 expired content
218 regular pages created
214 other pages created
2 non-page files copied
14 paginator pages created
15 categories created
180 tags created
total in 1083 ms
```

180 is way too much (and slows down the site build). Having so many tags is a misunderstanding of the taxonomy concept: These should be common concepts, not SEO keywords (use something else for that).

**Comment by rdwatters** [comment]
> Having so many tags is a misunderstanding of the taxonomy concept

I manage content every day, and I assure you, it's not. Keywords haven't been a heavy SEO consideration in years.

How about this? I'll take the list of 180 tags and pair it down to 40-50, then we can keep everything to those terms; i.e., rather than a folksonomy, it becomes a controlled vocabulary. I'll put it in a spreadsheet :smile: 

As an aside, "categories" reflect the current section. I did this only because I was moving files around a lot when first thinking about the IA and thought it might be a good future-proofing technique. We can modify as you see fit.

**Comment by digitalcraftsman** [comment]
When looking at https://next--gohugoio.netlify.com/tags/ I wouldn't like to search for the right tags. I agree with @bep that we trim the list of tags a bit.

**Comment by rdwatters** [comment]
Cool. I'll aim for 40-50 tags tops...

**Comment by bep** [comment]
I would say 20 tags tops.

**Comment by bep** [comment]
I like this one: https://next--gohugoio.netlify.com/tags/rysnc

**Comment by bep** [comment]
The thing is: With 20 tags it could be useful.

**Comment by bep** [comment]
@rdwatters I was hoping to use the docs site as a test/demo for my new search figure. Please do not commit to issues if you don't plan to follow up on it. I know this is open source and that people have families/school/work etc., but we're having 50+ open docs issues now. I have added the "important" label to some of them to indicate some that are overdue for a fix. It would be great with some helping hands.

/cc @digitalcraftsman

**Comment by bep** [comment]
@rdwatters what is the meaning of "thumbs up" in this case? Will you do this in the next few days of should I re-assign this?

**Comment by rdwatters** [comment]
I will take care of this in about 6 hours when I get home.

**Comment by bep** [comment]
@rdwatters I don't see any commits re. this, did you forget to commit?
