### ISSUE TITLE
Make external tutorials a first class citizen

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#449]
Like this:

https://forestry.io/blog/build-a-json-api-with-hugo/

We need a better way to link to those -- a standard way, more visible.

Which describes custom output formats much better than I did when I wrote the first version of the one on gohugo.io.

And @regisphilibert 

>If that doesn’t work, you may have to stop and restart the Hugo server.

I think the correct advice would be to run with `--disableFastRender`. But I kind of don't understand it. The liverload doesn't work for JSON -- but a CTRL + R should?

**Comment by regisphilibert** [comment]
You are right, refresh is pointless without `--disableFastRender`
But using `--disableFastRender` I still have to refresh to update the changes, is that normal?

**Comment by bep** [comment]
1) I don't think `--disableFastRender` should be needed. We should be smart enough about it. That sounds like a borderline bug and should be fixed.
1) Livereload is injected JavaScript .... which is HTML only.

**Comment by regisphilibert** [comment]
Back to original topic, I think it could be very helpful to add at the end of a documentation page a selection of "good reads" which dive in detail into the given topic/feature.

I think it may be more efficient into helping users than adding yet another section to the doc site listing a bunch of good reads unrelated to each other.

**Comment by bep** [comment]
>I don't see anything wrong with linking to things at the end of a post, 

I was more thinking in the line of a "see also" box in the middle somewhere, i.e. near the relevant section. I have done it in one or two places with the "note" shortcode, but I feel it gets a little bit buried.

**Comment by budparr** [comment]
So it could be as simple as this (perhaps but in a box to draw attention to it, or perhaps not).

<img width="470" alt="screen shot 2018-04-13 at 5 50 54 pm" src="https://user-images.githubusercontent.com/115347/38759310-43b6a634-3f43-11e8-8d3f-3ca031efdeed.png">

The articles could be listed in front matter, or perhaps collected in a data file and related back using tags.

**Comment by budparr** [comment]
I think better in a data file then related back. That seems more manageable and makes articles useful on more than one page.

**Comment by bep** [comment]
>I think better in a data file then related back. T

No, my gut feeling is still a shortcode, e.g. 1 link to a relevant article inside a section/paragraph.

**Comment by regisphilibert** [comment]
> No, my gut feeling is still a shortcode, e.g. 1 link to a relevant article inside a section/paragraph.

Yes I see your point. Beside it allows the editor to add a short sentence describing how this reference can help the user at this point in the doc.

**Comment by kaushalmodi** [comment]
@budparr This came up earlier in a separate thread too. I believe that data files are a better way to do this. That way you have a single point of controlling all external post references, rather than going within each doc file and manually adding it.

The data file can have a simple structure like:

```
[doc-file-basename]
  # ref 1
  [[doc-file-basename.ref]]
    author = "Foo Bar"
    url = "https://awesome.ref/"
    summary = """
    Interest-invoking a bit detailed summary.. may be a line or two 
    telling the readers why they might find that external ref useful.
    Can contain **Markdown** too.
    """
  # ref 2
  [[doc-file-basename.ref]]
  ...
```

Then in the `single.html` or equivalent for the doc site pages, you simple

**Comment by regisphilibert** [comment]
I think the shortcode vision works great because, the post in question may not be about the whole page presently being read by the user.
Some post may only focus on one method or one particular usage of such method.

In this sense, we should design a sort of unique `note` shortcode which would provide at a glance, reasons for why the reader could or could not benefit from reading the post. I am no designer :( but something along: 

--------
Read on 
--------
For more information on how to use whatever in such context.

📑 __Link__
-------

--------
Read on 
--------
- Practical examples
- Tutorial

📑 __Link__
-------

**Comment by budparr** [comment]
I definitely see your point. The two approaches aren't mutually exclusive, but ultimately, we just need to find ways to make more concrete examples available and give users an easy way to find them.
