### ISSUE TITLE
Document new per-language contentDir (Hugo v0.38), and add a comprehensive tutorial on multilingual website

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/hugoDocs#471]
See https://gohugo.io/news/0.38-relnotes and https://gohugo.io/news/0.38.2-relnotes, for example.

Right now, multilingual related features seem to be (from my vague memory) separated on a few different pages that are not linked with one another.

Also investigate `defaultContentLanguageInSubdir` because I still don't fully understand it.

**Comment by regisphilibert** [comment]
Hey there! Can't promise a delivery date but I'd love to document this feature.
I'll dive into it (using bep's comments in https://github.com/gohugoio/hugo/commit/eb42774e587816b1fbcafbcea59ed65df703882a as reference) and come back if some question pop up.

**Comment by regisphilibert** [comment]
Just to clarify how Page Bundle are treated here:

`/content/english/about/index.md` > English
`/content/french/about/index.md` > French, linked with content file above

`/content/english/about/index.md` > English
`/content/french/about.md` > French, not inked with content file above

**Comment by regisphilibert** [comment]
I just want to make sure I fully comprehend how this works. Most of it is explained by @bep in the commit comment, but the Page Bundles are left out. This is what I understand about how Page Bundles are being treated shall we opt for a "language per directory" content structure:

`/content/english/about/index.md` > English 
`/content/french/about/index.md` > French, **linked** with content file above 

`/content/english/about/index.md` > English 
`/content/french/about.md` > French, **not inked** with content file above (shouldn't it be linked?)

It appears in the templates, Page Bundles from both languages are treated as one big bundle, each linked page being able to access the other one's Resources. This is great :)
One exception is for files with the same name (relative path?) being present in both Bundles. In this case only the resource from the page being treated is returned by `.Resources`. 
This is also great, because in many cases, you will look for say a "header" file which may or may not be different depending on your language.

Also:
> Also investigate defaultContentLanguageInSubdir because I still don't fully understand it.

From what I understand, you have to set it to true if your default language directory is not at the root of your project. (as in the `content/english`, `content/norwegian` exemple). 
Why do we need this set when the language `contentDir` is defined in the language param, I don't know... Maybe @bep can explain so we can mention this in the doc, this seems important.

I'll post this comment and hopefully won't need any more clarification.

**Comment by bep** [comment]
Your first question:

* For bundles, the content files (*.md, *.html etc) are per language. You will not inherit a content file in another language.
* All the other files (images, JSON files, whatever) will either pick the current language version or the first version in the other languages (ordered by language sort).
* One use case of the above is to avoid duplicating images when translating bundles.

`defaultContentLanguageInSubdir` is not related to this particular change.

The default is:

* http://example.com (main language, often English)
* http://example.com/no (Norwegian)

If you set:

`defaultContentLanguageInSubdir = true``

You will get:

* http://example.com/en
* http://example.com/no

And then there is the multihost support, which will be:

* http://example.com
* http://example.no

**Comment by regisphilibert** [comment]
Thanks for clarifying! 

One last question regarding this sentence you wrote in your code comments:

> The value of `contentDir` can be any valid path, even absolute path references. The only restriction is that the content dirs cannot overlap.

Why do you mean by "absolute path references"?

**Comment by regisphilibert** [comment]
So I was recently playing with string translation and I have a question which may lead to improving this section of the doc or not...

There seems to be two way to write `i18n`

This way:
```
- id: horse
  translation: Cheval
[ ... ]
```
And this way:
```
- horse
  other: Cheval
[ ... ]
```
Those two are not interchangeable, I cannot use `translation` key for one string, and `other` key for one thing. 

I cannot remember how I got started with localizing my projects, but I only knew and used the first one.
Is there a reason for keeping the first one aside from code breaking, and if not, shall we advertise against it? I think we should discreetly as any one using the first one will have to rewrite all its `i18n` files shall they need to handle pluralized strings.

**Comment by bep** [comment]
@regisphilibert I would say that your last question(s) are out of scope for this particular issue.

**Comment by regisphilibert** [comment]
You are right, I'll reformulate in a separate one. Sorry about that.

**Comment by regisphilibert** [comment]
https://github.com/gohugoio/hugoDocs/issues/510

**Comment by regisphilibert** [comment]
When I created the PR I thought the only way to localize Page Resources was to use the "placement" or "per directory" content management. But it appears you can link two resources together by filename just like with any other content file.

```
 └── about
    ├── index.md
    ├── index.fr.md
    ├── index.es.md
    ├── header.jpg
    └── header.es.jpg
```

I will have to rework the piece to reflect this, when I'm done, I'll merge it myself if no one object.

I'm also going to publish a "companion" tutorial on Multilingual in two parts (1. Content Translation, 2. String Translation) starting next week I think. This will be a great to dive into examples and use cases.

**Comment by regisphilibert** [comment]
I just merged.
