### ISSUE TITLE
Add docs for Hugo Pipes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#524]
We need some proper documentation for Hugo Pipes, but I think we should agree on a "disposition". I think we should make it its own section -- dumping it into the "functions" will be confusing.

So:

* Hugo Pipes
  * Overview
  * SCSS/SASS
  * PostCSS
  * Assets minification
  * Assets bundling
  * Fingerprinting and SRI
  * Create a Resource from a template
  * Create a Resource from a string

The order above is a little bit random. 

/cc @kaushalmodi @regisphilibert @digitalcraftsman  and gang.

**Comment by regisphilibert** [comment]
> I think we should make it its own section

Oh yes!

**Comment by regisphilibert** [comment]
I think this should be done sooner than later and propose adding a one page listing all possible functions with their arguments and basic usage this week. Then we can work on thickening the section later. What people are struggling the most with these days is figuring out the functions arguments, so that's my priority.

@bep, here is my understanding the various functions and their arguments (I list them in brackets except for the obvious resource input). I'm sorry if my questions are scattered among the following doc outline, but this is me working fast with a low bandwith cabin.

**Get [file path]**
Grab the resource for later use/transformation

FromString [input is a string, destination path]

**ToCSS [map of options]**
Known options are `targetPath` and `enableSourceMap`. Any other we should know about? Are those part of an option set from the used sass lib, or defined by Hugo core?
Turn a sass or scss file into CSS. Filesystem (project, themes and theme components hierarchy) works only one level deep: 
If the file contains an `@import "what.scss", `what.scss` can be overridden by project or theme component's own `what.scss`. But if the file contains `@import "components/what.scss"`. `components/what.scss` is not overridden. This is based on my own test, but needs confirmation.
The default destination is the file's path rel. to assets + .css.

**Minify [map of options?]**
Minifies a css | js | json | html | svg | xml file. 
The "default" (I don't think it is changeable) destination is the file's path rel. to assets + .min . + original extension.

**Fingerpint [map of options?]**
Creates a fingerprinting version of the file (meaning only the permalink is transformed ?). Plus `.Data.Integrity` key is added with a sha254 value.

**Concat [slice of resources, destination path]**
Concatenate resources of the same media type. 

**PostCSS [slice of options]**
Known option is "configPath".
Uses project's or theme's `config.post.css` to process given css resource. (needs used node dependencies installed, postcss-cli dep is mandatory)

**ExecuteAsTemplate [destination path, context]**
I think I understand this one clearly.

**Comment by rdwatters** [comment]
Independent section sounds like a good idea, but documentation titling (and nav labels) should be based on what is most intuitive to new users. I’d recommend calling this section “assets” or “asset management” and including documentation around images in here as well. Of course, introduce the concept of “Hugo pipes” in the content itself :smile:

**Comment by bep** [comment]
Most of these should have their options explained in GoDoc, e.g. https://godoc.org/github.com/gohugoio/hugo/resource/tocss/scss
https://godoc.org/github.com/gohugoio/hugo/resource/minifiers

Also, I think it helps to use the same terms as in the code -- e.g. `targetPath` and not "destination path".

Re PostCSS:

I think there is a bug here at the moment. but it should look both in project and theme for the config file, and defaults to postcss.config.js if not set in options.

I have no idea what you are talking about re. what.scss. The core part about this is that the root folder of the SCSS in project and themes are added as import paths to SASS. I must admit that I have not tested too many import override variations -- but if there are obvious limitations in this area, we should fix that and not mock around with it in this issue.

**Comment by regisphilibert** [comment]
> Most of these should have their options explained in GoDoc, e.g.

This is what I needed. Thanks.

> I’d recommend calling this section “assets” or “asset management” and including documentation around images in here as well.

I agree.

**Comment by bep** [comment]
Let us use the section/names as given by my first post.

**Comment by regisphilibert** [comment]
I'm tempted to simply drop the link pointing to the [package options you provided](https://godoc.org/github.com/gohugoio/hugo/resource/tocss/scss#Options) rather than listing them so the doc can remain unchanged if the package is updated, what do you guys think?

**Comment by bep** [comment]
>I'm tempted to simply drop the link pointing to t

It was meant as a source of reference for **you**

**Comment by regisphilibert** [comment]
I think I have something that works and will submit a PR tomorrow after a post-sleep last read, so I can be responsive to comments.

> Let us use the section/names as given by my first post.

The subsection are spot on because this is what people will be looking for: How do I __minify__ or __bundle__ my assets using Hugo? I used them as is and this works great.

I think _Hugo Pipes_ on the other hand, is not what people will be looking for, and, as we don't want __Hugo__ to prepend any doc menu item, the new sidebar item would simply read __Pipes__ which will not speak much to anyone not familiar with Hugo's news cycle.

**Comment by bep** [comment]
>we don't want Hugo to prepend any doc menu item

Who is "we"? I want that, so it does not include all.

**Comment by bep** [comment]
What should be the section name (top level menu title) for the documentation we discuss in this thread:

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Assets)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Assets/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Assets%20Management)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Assets%20Management/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Hugo%20Pipes)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Hugo%20Pipes/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Pipes)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01CJPACQHM1Y46S59JQC48XW1Z/Pipes/vote)

**Comment by regisphilibert** [comment]
Here it is: https://github.com/gohugoio/hugoDocs/pull/531

**Comment by Jos512** [comment]
Hmm. I'm thinking that if we call this 'Hugo Pipes', we'll need to revisit the [pipes](https://gohugo.io/templates/introduction/#pipes) explanation too. It won't help beginners if we have 'Hugo Pipes' and 'Pipes'?
