### ISSUE TITLE
Theme "hugo-minimalist" is 404.

### ISSUE THREAD

**Issue by Tazeg** [gohugoio/hugoDocs#581]
Hello, the button DEMO at https://themes.gohugo.io/hugo-minimalist/ is 404.

**Comment by digitalcraftsman** [comment]
Hello @Tazeg,

this issue is already known to us and affects other themes as well.  Right know we're investigating this issue to find it's cause. Due to the number of affect themes it's most likely something on our end.

You can find the corresponding issue [here](https://github.com/gohugoio/hugoThemes/issues/412). Hence I'll close this issue as a duplicate.

Thank you.
