### ISSUE TITLE
The .Format page should use a different date.

### ISSUE THREAD

**Issue by RichMorin** [gohugoio/hugoDocs#589]
The "Hugo Date and Time Templating Reference" section in the [.Format](https://gohugo.io/functions/format/) page uses the date "2017-03-03T14:15:59-06:00".  Because the month and day numbers are both 3, the reader is sometimes forced to guess which one is being displayed where.

For clarity, each portion of the date should have a different numeric value. For example:

    2000-01-02T03:04:05-06:07

**Comment by StephenBrown2** [comment]
`2017-03-03T14:15:59-06:00` is in iso8601 format, so it should be pretty clear what the values are, but I would agree with using different values, as farther down the page, an example of Go's Date format string is used: https://gohugo.io/functions/format/#go-s-layout-string

Since HugoDocs uses hugo, could perhaps that string be printed using a template string, and updated on each build?
