### ISSUE TITLE
Improve "upcoming event" example

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#593]
See example in https://gohugo.io/templates/introduction/#example-show-only-upcoming-events

I suspect this can be rewritten to something like:

```bash
{{ $pages :=  where .Pages "Section" "events" }}
{{ $pages := $pages | intersect (where .Pages "Date" "<=" now) }}
{{ range $pages.ByDate }}
```

The above is totally untested but looks cleaner in my head. 

/cc @kaushalmodi

**Comment by francisco-core** [comment]
Thank you @bep. I spent more than two hours looking for a way to show just the first upcoming event and with the version on the website (https://gohugo.io/templates/introduction/ in the bottom) it was getting way too confusing.

with a simple adaptation I was able to figure it out:
```html
  {{ $pages :=  where .Pages "Section" "events" }}
  {{ $pages := $pages | intersect (where .Pages "Date" ">=" now) }}
  {{ range first 1 $pages.ByDate }}
```

So yes, I think this approach is better as it allows for some easier modifications and understanding

**Comment by jmooring** [comment]
In addition to syntax changes, this example should be based on `.Page.Params.event_date` instead of `.Date`. If you use `.Date` to represent an event date, you have to build the site with the `--buildFuture / -F` option to render future events.

Additionally, the example should (if possible) be front matter format agnostic. Dates in TOML are first class citizens, making date comparisons simple. Dates as strings (JSON, YAML, or quoted TOML) are not as simple to compare.
