### ISSUE TITLE
Document Go template's multiline support

### ISSUE THREAD

**Issue by bep** [gohugoio/hugoDocs#764]
So, I didn't know about this, and so I suspect others also don't know about this.

```bash
{{ $multiline := `This is a line.
This is another.` }}

{{ $multiline }}
```

/cc @regisphilibert

**Comment by regisphilibert** [comment]
Nice, I'll play around with this to understand its advantage. There may be more than storing a multiline string in a variable.

**Comment by regisphilibert** [comment]
This will be soon replacing lengthy `dict` call

```
{{ $person := `{ 
	"name": "John Doo",
	"occupation": "laying there"
}` | transform.Unmarshal }}
{{ $person.name }}
```

**Comment by bep** [comment]
This would be great to get fixed https://github.com/golang/go/issues/29770

**Comment by regisphilibert** [comment]
👆 The above examples worked successfully. I've not tested them with deeper content but I don't see what kind of data coud break them.

Let me know if you think such a "hint" belongs in the doc. Otherwise I'll simple add the fact that you can use multiline in "backticked" strings even though I can't come up with too many uses cases for this...

**Comment by bep** [comment]
It think it's important that it's in the doc once and it's searchable (i.e. below a header) that says "Multiline strings in template" or something. Because people will have this problem -- and search for it.

**Comment by pjeby** [comment]
I found a somewhat better way to do multiline dicts with expressions:

```
{{ with dict `` `
  ` "title"     $section_page.Title `` `
  ` "url"       $url `` `
  ` "highlight" (gt (len $child_pages) 0) `` `
  ` "content"   ($section_page.Summary | safeHTML) `` `
  ` "actions"   (slice (dict "label" "Learn More" "url" $url)) `` `
  ` -}}
  {{ partial "card" ( slice $ . ) }}
{{ end }}
```
It works by adding two raw strings between each key-value pair.

On the con side, this adds an empty key with a linefeed and some spaces to the resulting dictionary.  On the pro side, it doesn't add parsing overhead at runtime and preserves objects you can't marshal (like safeHTML or Page objects).  Still, supporting multiline action parsing directly would be much better still, since this approach doesn't really help for slices.

**Comment by bep** [comment]
@pjeby that looks clever -- may be a little bit hard to get right (copy and paste helps), but it's very readable once it is there. We could probably adjust `dict` to drop empty keys, maybe ...

**Comment by pjeby** [comment]
Now that hugo is vendoring the template package, we could just change the lexer and fix the whole problem at the source.  I was going to put a PR in (only like 3 or 4 lines changed outside of the tests), but then I noticed some verbiage about the code being autogenerated?  I looked around but couldn't find where it was being generated *from*, though.  Is there some strategy for updating the vendored code from upstream?

FWIW, the relevant lines in the lexer are [here](https://github.com/gohugoio/hugo/blob/master/tpl/internal/go_templates/texttemplate/parse/lex.go#L366) and [here](https://github.com/gohugoio/hugo/blob/master/tpl/internal/go_templates/texttemplate/parse/lex.go#L429) -- both regions look to just need to treat isEndOfLine the same as isSpace, and we should be golden.  I've also scoped out the relevant tests.

Anyway, I'd be happy to supply the PR, assuming that it's not going to break the vendoring strategy.  :wink:

**Comment by bep** [comment]
@pjeby  I would really like to to get my Go template changes "somehow" back into Go itself, and if that isn't possible, I'm restricting any patches to the "execution" side of these packages.

**Comment by pjeby** [comment]
Ah, so it'll have to wait for golang/go#29770 then, I guess.  I guess I was just hoping that the recent vendoring of the libs meant we were finally going to be breaking free of the tyranny of single-line actions.  :wink:

**Comment by bep** [comment]
Hmm.... That would have been nice to get fixed ...

**Comment by bep** [comment]
@pjeby to answer your question:

1. I'm pretty sure that a proper fix for golang/go#29770 would eventually be merged into Go.
2. If _someone_ created a proper fix for  golang/go#29770 (that passed Go's standards for tests etc.) I could probably be convinced to maintain a temporary patch in Hugo's tree.

**Comment by pjeby** [comment]
I'll look into it; the first hurdle I ran into was the whole "you need a google account with the same email as your commits" thing, which will only work if it's okay with recovery or alternate emails.  I will look into it further soon.

**Comment by pjeby** [comment]
So it turned out to be a much bigger job than I thought.  It's true that my 3-or-4 line fix worked, but then it occurred to me that the next issue people would have would be comments in the body of an action, and also probably issues with opening trim markers needing a trailing space that might be at end-of-line.

So I bit the bullet and refactored the lexer's scanning API, because it was *really* not meant to handle lookaheads > 1 rune, and there was an awful lot of manual pointer arithmetic going on down in there (including hacks to work around the 1-rune limit).  
 
Hopefully my refactoring won't make the PR less likely to be accepted; I *think* it should have the same performance (or maybe even better, since some things can now be inlined that weren't before, and the line number calculations are batched to once per token instead of once per character, but I don't know what the batch overhead is.  (In any case, to properly deal with flow lexing of comments, trim markers, and all the rest, some refactoring was necessary.)

Anyway, to make a long story not much longer, the branch is [here](https://github.com/pjeby/go/commits/template-flow) if you want to have a look and offer any suggestions before I actually submit this.  I've not yet written a properly formatted PR description, but that's on my list next, along with some reviewing of recent accepted and rejected PRs upstream so I can see what the process is really like, outside the docs. ;-) )

**Comment by pjeby** [comment]
Ok, I think it's done now.  See the [full diff here](https://github.com/golang/go/compare/master...pjeby:template-flow).  I'm gonna squash the commits before submitting a PR, but I'd like to solicit comments at this point.  This change:

* Makes all whitespace, including comments, to be equivalent in actions (outside of string or character constants), except that trim markers still require actual whitespace of some kind.  (It's just that the whitespace can be a tab, newline, or carriage return now.)
* Drops dedicated comment syntax, treating the existing comment syntax as a simple consequence of ignoring whitespace and comments in actions.  (So empty actions are now a no-op.)

In addition to these changes, I sped up the parse package's stress-testing benchmark by like 8%, though sometimes it randomly speeds up by 18% for reasons I don't understand.  But the 8% is compared to how fast the master branch goes when *it* randomly goes faster than usual for reasons I don't understand, so I think 8% is a reasonable improvement estimate.

In practice, though, since this is a difference between, like, 180k actions parsed/second vs. 195k actions/second, it's probably not gonna be all that noticeable in any real application.  :wink:

Anyway, this should help with not only making absurdly large expressions in Hugo templates, but also lets you add comments *within* said expressions so you can later understand just what it is you did.  :wink:

**Comment by bep** [comment]
>though sometimes it randomly speeds up by 18% 

I find that turning off any "turbo boost" when doing benchmarks helps keeping the results more consistent, e.g. http://tbswitcher.rugarciap.com/

>then it occurred to me that the next issue people would have would be comments in the body of an action, 

Like?

```
{{ dict 
/* Foo is bar */
"foo" bar"
}}
```

Is that allowed in the current version?

**Comment by pjeby** [comment]
If by current version, you mean my fork, then yes.  It isn't allowed in normal Go templates.

I added it because I was pretty sure it would be the first thing people would need/want/expect to be able to do once actions became multiline.

**Comment by bep** [comment]
> It isn't allowed in normal Go templates.

Which was what I meant by "current". I ask because I think a smaller change set would be easier to sell to the Go team. I have browsed your code, and I really like what I see, but it's not me that needs convincing. So, if this could be made into a considerably smaller change set without the comment patch, maybe that could be pulled out into its own?

**Comment by pjeby** [comment]
So such a change would look like [this](https://github.com/golang/go/compare/master...pjeby:space-only), basically.  I was worried it would look too bare, actually.  Though mainly my motivation was realizing that as soon as you can have multiline actions, people will want to do this:

```
...
{{-
   whatever
-}}
...
```

Except they *can't*, because there must be a trailing space on that first line, and a leading space on that last one.  So then it became "okay, so the trim markers should be whitespace agnostic", which then led to needing scanner changes, and then, "wait, why are comments a special case then?"

IOW, looking at it from the user's point of view, anything between the extremes of "one line only, comments are a special action" or "actions are free flowing like a normal programming language" seems weird and dysfunctional.

Granted, if weird and dysfunctional is all we can get, I guess I'll take it.  :wink:

**Comment by bep** [comment]
Just so I understand. This would work?

```
{{-SPACE
   whatever
SPACE-}}
```

?

I will take this for a spin later today to understand it better.

**Comment by pjeby** [comment]
That would work with either patch, yes.  The longer patch would not need the leading and trailing space, as it considers newlines to be suitable to denote whitespace trimming.

There is also now a [squashed version of the long patch](https://github.com/golang/go/compare/master...pjeby:flow-templates) with a proper commit message.

**Comment by jmbarbier** [comment]
This feature have landed in golang master : https://github.com/golang/go/commit/9384d34c58099657bb1b133beaf3ff37ada9b017

**Comment by davidsneighbour** [comment]
This seems to be a feature now for a while. Close it? @jmooring
