### ISSUE TITLE
Preloading of Missing Font - 404 error

### ISSUE THREAD

**Issue by Noki** [gohugoio/hugoDocs#796]
The html pages on gohugo.io and theme.gohugo.io currently preload font files that result in a 404:

```
<link rel=preload href=https://gohugo.io/files/muli-latin-200.woff2 as=font type=font/woff2 crossorigin>
<link rel=preload href=https://gohugo.io/files/muli-latin-400.woff2 as=font type=font/woff2 crossorigin>
<link rel=preload href=https://gohugo.io/files/muli-latin-800.woff2 as=font type=font/woff2 crossorigin>
```

Best regards
Tobias

**Comment by rhcarvalho** [comment]
This seems to be a problem in the theme template. Seems that the font assets were moved from `files/` to `fonts/` in #666. Going to submit a patch.

**Comment by rhcarvalho** [comment]
I think the theme in this repo and https://github.com/gohugoio/gohugoioTheme are out of sync. Tried running `pull-theme.sh` and got some conflicts.

Wondering if the preferred way is to fix the issue here or the other repo.

In fact, in https://github.com/gohugoio/gohugoioTheme the [font preload code has been removed (3b33d5ad)](https://github.com/gohugoio/gohugoioTheme/commit/3b33d5ad200c57f8adbaf75f9c54ca3cc0cc97f8#diff-0c8f747dec0e7ca5148ebe8907cfc781L5).

@bep would you be able to provide some guidance? Thanks!
