### ISSUE TITLE
Quick Start needs Improvement

### ISSUE THREAD

**Issue by eaigner** [gohugoio/hugoDocs#851]
It takes quite a bit for me to write this, but the docs are probably not the best to get anyone started. I used hugo over 3 years ago. I remember it was infuriating just to get the most simple page to work. Many colleagues had the same experience. Now it's 3 years later and I can't remember how anything works and am in the same position again.

Quite honestly you could throw the whole documentation out, because it just does not help at all. What I actually searched for is just how to render a few pages and hoped to understand how the templates are structured.

The quickstart gets you nowhere if you want to start from scratch and **don't** want to use some blog template. The docs could be replaced with a single page just quickly explaining the directory structure and how to render and link between 2 pages. Would make much more sense IMHO.

Also most of the examples are completely out of context. It shows a code snippet without almost any clue how that would fit into the puzzle.

I think a good start would be to at least generate a default directory structure and files on

    hugo new site quickstart

so someone can make heads and tails out of the structure right then and there. For instance when you create a site with `jekyll` you just immediately know how it works without ever having to consult a quick start.

**Comment by eaigner** [comment]
One whole day wasted.... still not able to produce a single page site with scss.... amazing...

**Comment by kaushalmodi** [comment]
This is not the place to vent out. Ask for help on the Hugo Discourse Forum: https://discourse.gohugo.io/.

Documentation improvement is always welcome. Please submit a PR with suggested changes.

**Comment by eaigner** [comment]
Submit a PR with suggested changes. Yeah... it would be great if I could do that, unfortunately I can't because the docs are a mess. Thanks!

**Comment by rdwatters** [comment]
How about rather than a PR, you submit some recommendations for improved site structure, messaging, content hierarchy, search experience, UX, or otherwise. 

Recommending all documentation be a single page is not only a terrible practice (and makes the site less SEO friendly and linkable), it’s a format recommendation rather than a viable content strategy. Other than saying it’s terrible, can you make recommendations for improvements? This is an open-source project and those docs are the hard work of hundred of contributors. I think everyone is open to new insights and collaboration, but abject, unsolicited criticisms are going to fall on deaf ears for what are manifest reasons, @eaigner.

If you are having trouble getting started, have you tried the forums as well? I’m sure someone in the community will be more than happy to clone your project and help you with whatever solution you need😊

**Comment by eaigner** [comment]
I got it working after digging through several templates and "reverse-engineering" where hugo expects files and where it gets it's variables from. Like I said, the docs contributed absolutely nothing to getting me started. There is so much basic stuff missing.

Yet all that would be required is to fill the generated directory structure on

     hugo new site quickstart

with some minimal files.

But hey, who reads issue comments. Closing them is so much easier!

**Comment by budparr** [comment]
It's my understanding that most people who want a structure scaffolded for them use a minimal theme.

**Comment by bep** [comment]
@eaigner in some senses you have some valid points, but once you start with the "quite honestly you could throw the whole documentation out because it just does not help at all", this turns into an issue that isn't ... actionable. That statement is objectively not true in general.

**Comment by bep** [comment]
Continue this at https://discourse.gohugo.io/
